name: AFK
main: org.plugin.afk.AfkPlugin
version: 1.0
api-version: 1.21
author: ice
commands:
  afk:
    description: 进入/退出挂机状态
    usage: /afk
permissions:
  afk.admin:
    description: 允许使用 /afk <玩家> 开关他人挂机
    default: op
